/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AllRecipesRouteImport } from './routes/allRecipes'
import { Route as AddRecipeRouteImport } from './routes/addRecipe'
import { Route as IndexRouteImport } from './routes/index'

const AllRecipesRoute = AllRecipesRouteImport.update({
  id: '/allRecipes',
  path: '/allRecipes',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRecipeRoute = AddRecipeRouteImport.update({
  id: '/addRecipe',
  path: '/addRecipe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addRecipe': typeof AddRecipeRoute
  '/allRecipes': typeof AllRecipesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addRecipe': typeof AddRecipeRoute
  '/allRecipes': typeof AllRecipesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addRecipe': typeof AddRecipeRoute
  '/allRecipes': typeof AllRecipesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/addRecipe' | '/allRecipes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/addRecipe' | '/allRecipes'
  id: '__root__' | '/' | '/addRecipe' | '/allRecipes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRecipeRoute: typeof AddRecipeRoute
  AllRecipesRoute: typeof AllRecipesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/allRecipes': {
      id: '/allRecipes'
      path: '/allRecipes'
      fullPath: '/allRecipes'
      preLoaderRoute: typeof AllRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addRecipe': {
      id: '/addRecipe'
      path: '/addRecipe'
      fullPath: '/addRecipe'
      preLoaderRoute: typeof AddRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRecipeRoute: AddRecipeRoute,
  AllRecipesRoute: AllRecipesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
